import { KnowledgeBase } from './knowledge-base.entity';

export const KNOWLEDGE_BASE_SEED: Partial<KnowledgeBase>[] = [
  // ── GENERAL ────────────────────────────────────────────────────
  { category: 'faq', subcategory: 'general', question: 'What is insurance?', answer: 'Insurance is a financial safety net. You pay a small amount regularly (called a premium) to an insurance company. If something bad happens — fire, accident, theft, illness — the company pays you back so you don\'t lose everything. Think of it as paying a little to protect a lot.', keywords: ['insurance', 'what', 'definition', 'meaning'] },
  { category: 'faq', subcategory: 'general', question: 'Why do I need insurance in Nigeria?', answer: 'Nigeria has unpredictable risks — flooding, fire outbreaks, road accidents, theft. Without insurance, one bad event can wipe out years of savings. Insurance protects your business, family, and assets. Some types like motor insurance are also legally required by law.', keywords: ['need', 'nigeria', 'why', 'important'] },
  { category: 'faq', subcategory: 'general', question: 'What is a premium?', answer: 'A premium is the amount you pay for your insurance coverage. You can pay monthly, quarterly, or annually. The amount depends on what you\'re insuring and the level of risk. For example, motor insurance premiums depend on your car\'s value and type of coverage.', keywords: ['premium', 'payment', 'cost', 'price'] },
  { category: 'faq', subcategory: 'general', question: 'What is a policy?', answer: 'An insurance policy is your contract with the insurance company. It states exactly what is covered, what is not covered, how much you\'ll be paid if you claim, and the premium you pay. Always read your policy document carefully before signing.', keywords: ['policy', 'contract', 'document', 'agreement'] },
  { category: 'faq', subcategory: 'general', question: 'What is an excess or deductible?', answer: 'An excess (also called deductible) is the amount you pay out of your own pocket before insurance pays the rest. For example, if your excess is ₦50,000 and your claim is ₦500,000, insurance pays ₦450,000. Higher excess = lower premium.', keywords: ['excess', 'deductible', 'self', 'pay'] },
  { category: 'faq', subcategory: 'general', question: 'What is NAICOM?', answer: 'NAICOM (National Insurance Commission) is the government body that regulates all insurance companies in Nigeria. They ensure insurers are financially stable and treat customers fairly. Always verify your insurer is NAICOM-licensed at naicom.gov.ng before buying any policy.', keywords: ['NAICOM', 'regulator', 'government', 'licensed', 'regulate'] },
  { category: 'regulation', subcategory: 'general', question: 'Which insurance types are compulsory in Nigeria?', answer: 'Nigerian law requires: 1) Third Party Motor Insurance (all vehicles), 2) Builders Liability (buildings under construction), 3) Occupiers Liability (public buildings open to visitors), 4) Group Life Insurance for employees (minimum 3x annual salary), 5) Healthcare Workers Professional Indemnity. Violating these can result in fines or prosecution.', keywords: ['compulsory', 'mandatory', 'law', 'required', 'legal'] },

  // ── MOTOR ──────────────────────────────────────────────────────
  { category: 'policy', subcategory: 'motor', question: 'What is Third Party Motor Insurance?', answer: 'Third Party Motor Insurance covers damage or injury you cause to OTHER people and their property while driving. It does NOT cover damage to your own vehicle. It is the minimum legal requirement under Nigerian law (FRSC enforces this). Cost: ₦5,000–₦15,000 per year for most vehicles.', keywords: ['third party', 'motor', 'car', 'vehicle', 'minimum', 'legal'] },
  { category: 'policy', subcategory: 'motor', question: 'What is Comprehensive Motor Insurance?', answer: 'Comprehensive Motor Insurance covers BOTH third party damage AND damage to your own vehicle — from accidents, theft, fire, flood, and vandalism. It costs 2–5% of your vehicle\'s value per year. Best for newer or high-value vehicles. Example: A ₦5,000,000 car = ₦100,000–₦250,000/year.', keywords: ['comprehensive', 'motor', 'full cover', 'own damage', 'theft'] },
  { category: 'faq', subcategory: 'motor', question: 'What documents do I need for motor insurance?', answer: 'To buy motor insurance you need: Vehicle licence, proof of ownership (receipt or transfer papers), valid driver\'s licence, your National ID or BVN. For claims you\'ll also need the police report (for accidents/theft) and an accident report form from the insurer.', keywords: ['documents', 'motor', 'required', 'papers', 'certificate'] },
  { category: 'faq', subcategory: 'motor', question: 'What is NOT covered by motor insurance?', answer: 'Common motor insurance exclusions: 1) Driving under influence of alcohol/drugs, 2) Using a private vehicle for commercial purposes (e.g., Bolt/Uber without commercial policy), 3) Unlicensed driver, 4) War or nuclear risks, 5) Mechanical breakdown, 6) Wear and tear. Always read your policy exclusions carefully.', keywords: ['exclusions', 'not covered', 'motor', 'exceptions', 'invalid'] },

  // ── HEALTH ─────────────────────────────────────────────────────
  { category: 'policy', subcategory: 'health', question: 'What is HMO health insurance?', answer: 'An HMO (Health Maintenance Organisation) manages your healthcare. You pay a monthly or annual premium and get access to a network of hospitals and clinics. The HMO pays your medical bills directly — you don\'t pay out of pocket for covered treatments. Popular HMOs in Nigeria include Leadway Health, AXA Mansard, and Hygeia.', keywords: ['HMO', 'health', 'hospital', 'medical', 'maintenance'] },
  { category: 'policy', subcategory: 'health', question: 'What does health insurance typically cover in Nigeria?', answer: 'Standard health insurance in Nigeria covers: outpatient consultations, inpatient hospital admission, surgery, laboratory tests, X-rays, maternity care (with some plans), and prescription drugs. Most plans have annual limits ranging from ₦500,000 to ₦5,000,000 depending on the plan tier.', keywords: ['health', 'covers', 'hospital', 'treatment', 'benefit'] },
  { category: 'faq', subcategory: 'health', question: 'What is not covered by health insurance in Nigeria?', answer: 'Common health insurance exclusions: pre-existing conditions (usually excluded for 12–24 months), cosmetic surgery, fertility treatments, experimental treatments, injuries from self-harm or drug abuse, dental and optical (unless specifically included), and chronic conditions like diabetes in some basic plans.', keywords: ['health', 'exclusions', 'not covered', 'pre-existing'] },

  // ── LIFE ───────────────────────────────────────────────────────
  { category: 'policy', subcategory: 'life', question: 'What is life insurance and how does it work?', answer: 'Life insurance pays a lump sum (called the sum assured) to your chosen beneficiaries when you die. You pay a regular premium while alive. The payout helps your family cover living expenses, children\'s education, debts, or funeral costs. It\'s financial protection for the people who depend on you.', keywords: ['life', 'death', 'beneficiary', 'payout', 'family'] },
  { category: 'policy', subcategory: 'life', question: 'What is Term Life Insurance?', answer: 'Term Life Insurance covers you for a fixed period (e.g., 10, 20, or 30 years). If you die within that period, your family receives the payout. If you survive, the policy ends with no payout. It\'s the most affordable life insurance — ₦30,000–₦80,000/year for ₦5,000,000 cover for a healthy 35-year-old.', keywords: ['term life', 'temporary', 'period', 'affordable'] },
  { category: 'policy', subcategory: 'life', question: 'What is Whole Life Insurance?', answer: 'Whole Life Insurance covers you for your entire lifetime. It pays out whenever you die — no time limit. It\'s more expensive than term life but guarantees a payout. Some whole life policies also build cash value over time that you can borrow against.', keywords: ['whole life', 'permanent', 'lifetime', 'cash value'] },
  { category: 'faq', subcategory: 'life', question: 'How much life insurance do I need?', answer: 'A common rule: get life insurance worth 10x your annual income. If you earn ₦2,000,000/year, aim for ₦20,000,000 in coverage. Also consider: outstanding debts (mortgage, loans), number of dependents, children\'s future education costs, and your spouse\'s earning capacity. Always review your coverage as life changes.', keywords: ['how much', 'life', 'amount', 'coverage', 'enough'] },

  // ── PROPERTY / FIRE ────────────────────────────────────────────
  { category: 'policy', subcategory: 'property', question: 'What is Fire and Burglary Insurance?', answer: 'Fire and Burglary Insurance protects your building, contents, and stock from fire damage and break-ins. It covers: fire and smoke damage, theft by breaking in (burglary), damage caused by burglars, and some policies include lightning and explosion. Essential for any business with physical premises. Cost: ₦15,000–₦60,000/year.', keywords: ['fire', 'burglary', 'property', 'shop', 'theft', 'break-in'] },
  { category: 'policy', subcategory: 'property', question: 'What is All Risks Insurance?', answer: 'All Risks Insurance provides broad coverage for your property against almost any accidental loss or damage. Unlike fire insurance which covers specific events, All Risks covers anything UNLESS specifically excluded. Good for high-value items like equipment, electronics, and goods. The name is slightly misleading — it covers most but not all risks.', keywords: ['all risks', 'all risk', 'broad', 'comprehensive property', 'equipment'] },
  { category: 'faq', subcategory: 'property', question: 'Does property insurance cover flooding in Nigeria?', answer: 'Standard fire insurance does NOT cover flooding in Nigeria. You need a separate Flood Insurance add-on or a specialized policy. Given Nigeria\'s flooding challenges (especially in Lagos, Ibadan, Port Harcourt), flood cover is highly recommended for ground-floor businesses and homes in flood-prone areas. Ask your insurer specifically about flood cover.', keywords: ['flood', 'water', 'property', 'flooding', 'Nigeria'] },

  // ── SME / BUSINESS ─────────────────────────────────────────────
  { category: 'policy', subcategory: 'sme', question: 'What is a Business Owner\'s Policy (BOP)?', answer: 'A Business Owner\'s Policy bundles multiple coverages into one affordable package for SMEs: property insurance (fire, burglary), public liability (customer injuries), and business interruption (lost income if forced to close). Buying them together is cheaper than separately. Ideal for shops, restaurants, small offices, and service businesses. Cost: ₦40,000–₦150,000/year.', keywords: ['BOP', 'business', 'policy', 'bundle', 'SME', 'owner'] },
  { category: 'policy', subcategory: 'sme', question: 'What is Public Liability Insurance?', answer: 'Public Liability Insurance protects your business if a customer, visitor, or member of the public is injured on your premises or due to your business activities. Example: A customer slips and falls in your shop. Without this cover, you pay all medical and legal costs. With it, the insurance pays. Essential for any business that receives customers. Cost: ₦10,000–₦40,000/year.', keywords: ['public liability', 'customer', 'injury', 'premises', 'third party'] },
  { category: 'policy', subcategory: 'sme', question: 'What is Business Interruption Insurance?', answer: 'Business Interruption Insurance (also called loss of profits insurance) replaces your income when your business cannot operate due to a covered event like fire or flood. Example: Your shop burns down in January. Rebuilding takes 3 months. Business Interruption pays your lost revenue during those 3 months. Usually bundled with Fire insurance. Critical for businesses that would struggle to survive a forced closure.', keywords: ['business interruption', 'loss of income', 'closure', 'revenue', 'profits'] },
  { category: 'policy', subcategory: 'sme', question: 'What is Goods in Transit Insurance?', answer: 'Goods in Transit Insurance covers your goods, stock, or merchandise while being transported by road, rail, sea, or air. It covers loss, theft, or damage during transit. Essential for importers, distributors, e-commerce sellers, and any business that ships goods regularly. Cost: 0.5–1.5% of goods value per shipment.', keywords: ['goods in transit', 'transport', 'shipping', 'delivery', 'cargo'] },
  { category: 'policy', subcategory: 'sme', question: 'What is Professional Indemnity Insurance?', answer: 'Professional Indemnity (PI) Insurance protects professionals against claims of negligence, errors, or omissions in their services. If a client suffers financial loss because of your professional advice or services, PI covers your legal defence and any compensation. Essential for lawyers, accountants, consultants, doctors, architects, and IT professionals.', keywords: ['professional indemnity', 'PI', 'negligence', 'professional', 'consultant', 'error'] },

  // ── CLAIMS ─────────────────────────────────────────────────────
  { category: 'claims', subcategory: 'general', question: 'How do I file an insurance claim?', answer: 'Step 1: Report immediately — notify your insurer within 24–48 hours of the incident. Step 2: Document everything — take photos/videos, get witness contacts. Step 3: File a police report for theft, accidents, or major incidents. Step 4: Complete the claim form from your insurer. Step 5: Submit all evidence (photos, receipts, police report). Step 6: Cooperate with the assessor. Step 7: Review and accept the settlement. Most valid claims are settled within 5–30 days.', keywords: ['claim', 'file', 'submit', 'how', 'process', 'steps'] },
  { category: 'claims', subcategory: 'general', question: 'Why do insurance claims get rejected?', answer: 'Common reasons claims are rejected: 1) Late reporting (past the time limit), 2) Policy lapsed due to non-payment, 3) Incident is an excluded risk, 4) Fraud or misrepresentation, 5) Damage was pre-existing, 6) Repairing before the assessor visits, 7) Incomplete documentation (no police report, no receipts). Always report promptly and keep all documentation.', keywords: ['rejected', 'denied', 'claim', 'refused', 'failed', 'why'] },
  { category: 'claims', subcategory: 'general', question: 'How long does a claim take to be paid?', answer: 'Under NAICOM regulations, valid claims must be paid within 90 days. In practice, straightforward claims (with complete documentation) are settled in 5–15 working days. Complex claims with investigations may take 30–60 days. If your insurer delays beyond 90 days without valid reason, you can file a complaint with NAICOM.', keywords: ['how long', 'claim', 'payment', 'duration', 'settle', 'time'] },
  { category: 'claims', subcategory: 'motor', question: 'What do I need for a motor insurance claim?', answer: 'For a motor insurance claim you need: 1) Police report (mandatory for accidents and theft), 2) Completed claim form from insurer, 3) Original insurance certificate, 4) Vehicle licence and driver\'s licence, 5) Photos of the damage, 6) Repair estimate from a certified garage, 7) Witness statements if available. Submit everything together to avoid delays.', keywords: ['motor claim', 'accident', 'documents', 'required', 'car claim'] },

  // ── REGULATION ─────────────────────────────────────────────────
  { category: 'regulation', subcategory: 'general', question: 'What are my rights as an insurance policyholder in Nigeria?', answer: 'As a policyholder you have the right to: 1) Receive your policy document within 30 days, 2) Cancel your policy and get a pro-rata refund, 3) File a complaint with NAICOM if your insurer is unresponsive, 4) Receive claim payments within 90 days, 5) Accurate information about what\'s covered and excluded, 6) Fair treatment under NAICOM\'s Market Conduct Guidelines.', keywords: ['rights', 'policyholder', 'entitlement', 'NAICOM', 'consumer'] },
  { category: 'regulation', subcategory: 'general', question: 'How do I verify an insurance company is legitimate in Nigeria?', answer: 'To verify a Nigerian insurer is legitimate: 1) Check NAICOM\'s website (naicom.gov.ng) for their list of licensed insurers, 2) Verify the company\'s RC number with CAC, 3) Confirm they\'re a member of the Nigerian Insurers Association (NIA), 4) Check for a physical office address and landline number (not just mobile), 5) Be wary of unusually cheap premiums — they\'re often a red flag for fake insurers.', keywords: ['verify', 'legitimate', 'fake', 'scam', 'licensed', 'real'] },
];
